services:
  solr:
    environment:
      SOLR_SITES:
    volumes:
      - '${DDEV_APPROOT}/.platform/solr_configsets:/solr-configsets:ro'
    entrypoint: ['bash', '/mnt/ddev_config/solr/create-or-refresh-cores.sh']
