<?php

namespace Maestro\Hosting\Provider;

use Maestro\Core\FilesystemInterface;
use Maestro\Core\ProjectInterface;
use Maestro\Core\Utils;
use Maestro\Hosting\Hosting;
use Symfony\Component\Console\Style\StyleInterface;

/**
 * Provides hosting setup and configuration for DDev.
 */
class DDev extends Hosting {

  /**
   * {@inheritdoc}
   */
  public function build(StyleInterface $io, FilesystemInterface $fs, ProjectInterface $project) {
    parent::build($io, $fs, $project);
    $data = [];
    $solr_sites = [];

    // DDEV project name must not contain spaces.
    $data['name'] = Utils::createApplicationId(str_replace(' ', '.', $project->name()));

    // Generate site specific settings.
    foreach ($project->sites() as $site_id => $site) {

      // Multisite hosts.
      $data['additional_hostnames'][] = $site_id;

      // Create solr command for multiple cores.
      if (!empty($site['solr'])) {
        $solr_sites[] = $site_id;
      }
    }

    $solr_data = $fs->read($this->resourcesPath() . '/templates/docker-compose.solr_extra.yaml');
    $solr_data['services']['solr']['environment']['SOLR_SITES'] = implode(' ', $solr_sites);

    $fs->createDirectory('/.ddev');

    // Copy the base configuration for DDev.
    $io->writeln("Creating DDev base configuration file.");
    $fs->copy($this->resourcesPath() . '/templates/config.yaml', '/.ddev/config.yaml');

    // Create project specific DDev file.
    $io->writeln("Creating DDev project configuration file.");
    $fs->write('/.ddev/config.maestro.yaml', $data, TRUE);

    // Create Solr config.
    $io->writeln("Creating DDev Solr configuration file.");
    $fs->write('/.ddev/docker-compose.solr_extra.yaml', $solr_data, TRUE);

    if (!empty($solr_sites)) {
      $this->addInstructions('Generate and commit each site configset under .platform/solr_configsets/<site>/conf before starting DDEV.');

      $io->writeln("Copying Solr maintenance scripts to project.");
      $fs->copyDirectory($this->resourcesPath() . '/scripts', '/scripts/solr');
    }

    // Copy DDev resources to the project.
    $io->writeln("Copying DDev resources to project.");
    $fs->copyDirectory($this->resourcesPath() . '/files', '/.ddev');

    // Remove the fixed local Solr security policy generated by earlier
    // releases. DDEV Solr is intentionally credential-free.
    if ($fs->exists('/.ddev/solr/security.json')) {
      $io->writeln("Removing obsolete DDev Solr security policy.");
      $fs->delete('/.ddev/solr/security.json');
    }

    // Copy DDev Drupal services file if one doesn't already exist.
    if (!$fs->exists('/web/sites/default/services.yml')) {
      $io->writeln("Copying DDev Drupal services file.");
      $fs->copy($this->resourcesPath() . '/templates/drupal.services.yml', '/web/sites/default/services.yml');
    }

    // Create DDev provider.
    if ($project->type() == 'unity') {
      $provider_data = $fs->read($this->resourcesPath() . '/templates/ddev_provider_unity.yaml');
    } else if ($project->type() == 'corp-lite') {
      $provider_data = $fs->read($this->resourcesPath() . '/templates/ddev_provider_corplite.yaml');
    }

    foreach ($project->sites() as $site_id => $site) {
      $provider_data['db_pull_command']['command'] .= 'platform db:dump --yes ${PLATFORM_APP:+"--app=${PLATFORM_APP}"} --relationship=' . $site_id . ' --gzip --file=/var/www/html/.ddev/.downloads/db_' . $site_id . '.sql.gz --project="${PLATFORM_PROJECT:-setme}" --environment="${PLATFORM_ENVIRONMENT:-setme}"' . PHP_EOL;
      $provider_data['db_import_command']['command'] .= 'gzip -dc .ddev/.downloads/db_' . $site_id . '.sql.gz | ddev import-db --database=' . $site_id . ' --skip-hooks ' . PHP_EOL;
    }

    if (!empty($solr_sites)) {
      $provider_data['db_import_command']['command'] .= 'scripts/solr/configure-local-connectors --all' . PHP_EOL;
    }

    if ($project->type() == 'unity') {
      $fs->write('/.ddev/providers/unity.yaml', $provider_data, TRUE);
    } else if ($project->type() == 'corp-lite') {
      $fs->write('/.ddev/providers/corplite.yaml', $provider_data, TRUE);
    }


    // Create public files directory if one doesn't already exist.
    if (!$fs->exists('/web/files')) {
      $io->writeln("Creating Drupal public files directory.");
      $fs->createDirectory('/web/files');
    }

    // Create private files directory if one doesn't already exist.
    if (!$fs->exists('/private')) {
      $io->writeln("Creating Drupal private files directory.");
      $fs->createDirectory('/private');
    }

    // Check for an .env file and copy example if missing.
    if (!$fs->exists('/.ddev/.env')) {
      // Copy from the sample env file as it may have project specific entries.
      // If sample.env doesn't exist, copy the basic version.
      if (!$fs->exists('/.ddev/.env.sample')) {
        $fs->copy($this->resourcesPath() . '/templates/.env.sample', '/.ddev/.env.sample');
      }

      $fs->copy('/.ddev/.env.sample', '/.ddev/.env');
      $io->success('Created local .env file');
    }

    // Read .env file to check for some default Drupal environment settings.
    $env_data = $fs->read('/.ddev/.env');

    if (empty($env_data['HASH_SALT'])) {
      if ($io->confirm('Hash Salt was not found in the .env file. Would you like to add one?')) {
        $env_data['HASH_SALT'] = str_replace(['+', '/', '='], ['-', '_', ''], base64_encode(random_bytes(55)));
        $fs->write('/.ddev/.env', $env_data);
        $io->success('Creating local site hash within .env file');
      }
    }

    if (empty($env_data['PLATFORM_PROJECT'])) {
      $env_data['PLATFORM_PROJECT'] = $project->id();
      $fs->write('/.ddev/.env', $env_data);
    }

    if (empty($env_data['PLATFORM_ENVIRONMENT'])) {
      $env_data['PLATFORM_ENVIRONMENT'] = 'edge';
      $fs->write('/.ddev/.env', $env_data);
    }

    // Inform the user if composer install is needed.
    if (!$fs->exists('/vendor')) {
      $this->addInstructions("Run 'ddev composer install'");
    }

    // TODO: Write a per project provider and display usage instructions.
  }

}
